apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-deployment
  namespace: springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-boot-deployment
  template:
    metadata:
      labels:
        app: spring-boot-deployment
    spec:
      containers:
        - name: mysql
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: MYSQL_PASSWORD
          ports:
            - containerPort: 3306
