apiVersion: apps/v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: springboot
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA=== 
  MYSQL_DATABASE: dGVzdGRi
  MYSQL_USER: cm9vdA==
  MYSQL_PASSWORD: cm9vdA==
