apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: springboot
type: Opaque
data:
   MYSQL_ROOT_PASSWORD: cm9vdDEyMw==
   MYSQL_DATABASE: bXlkYg==
   MYSQL_USER: YXBwdXNlcg==
   MYSQL_PASSWORD: YXBwcGFzczEyMw==
