apiVersion: v1
kind: Service
metadata:
  name: spring-boot-deployment
  namespace: springboot
spec:
  selector:
    app: spring-boot-deployment
  type: NodePort
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
      nodePort: 30080

  #minikube service spring-boot-deployment  minikube to access api's