apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-deployment
  namespace: springboot

spec:
  replicas: 3

  selector:
    matchLabels:
      app: spring-boot-deployment

  template:
    metadata:
      labels:
        app: spring-boot-deployment

    spec:
      containers:
        - name: spring-boot-container
          image: likhith045/springboot-app:v1

          ports:
            - containerPort: 8085

          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/mydb

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: MYSQL_USER

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: MYSQL_PASSWORD
          
          livenessProbe:
            httpGet:
             path: /actuator/health
             port: 8085
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          
          readinessProbe:
            httpGet:
             path: /actuator/health
             port: 8085
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
