apiVersion: v1
kind: Service
metadata:
  name: spring-boot-deployment
  namespace: springboot
spec:
  selector:
    app: spring-boot-deployment
  type: NodePort

  
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
      nodePort: 30080

  #minikube service spring-boot-deployment -n springboot    minikube to access api's
  # ./run.cmd to run the self hosted runner 
  #d3JvbmdwYXNz 
