name: SpringBoot CI-CD

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build JAR
        run: mvn clean package -DskipTests

      - name: Build Docker Image
        run: docker build -t likhith045/springboot-app:v1 .

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: docker push likhith045/springboot-app:v1

      - name: Deploy to Minikube
        run: |
          kubectl apply -f k8s/mysql_deployment.yml
          kubectl apply -f k8s/my-sql-service.yml
          kubectl apply -f k8s/springapp-deployment.yml
          kubectl apply -f k8s/springapp-service.yml